version: "3.9"

services:
  warp:
    build:
      context: .
    image: my-warp-proxy:latest # اسم ایمیج برای کش شدن
    container_name: warp_proxy_module
    restart: unless-stopped
    # استفاده از بریج برای ایزوله بودن ماژول (استانداردتر از هاست است)
    ports:
      - "10808:10808"
    volumes:
      # ذخیره وضعیت اکانت
      - warp_data:/etc/xray/wgcf
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1

volumes:
  warp_data:
