version: "3.9"

services:
  warp:
    build:
      context: .
    image: my-warp-proxy:latest
    container_name: warp_proxy_module
    restart: unless-stopped
    ports:
      # Map Host Port to Container Port dynamically
      - "${XRAY_PORT:-10808}:${XRAY_PORT:-10808}"
    volumes:
      - warp_data:/etc/xray/wgcf
    env_file:
      - .env
    environment:
      - XRAY_PORT=${XRAY_PORT:-10808}
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1

volumes:
  warp_data:
